"""
Django settings for capstone project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-vyk!nxvpt#f*=7-hnoi-2&_^fq#kyr=3p00t!h$o4l!8%nk4vh"

#==========================================================#
# 뉴스 API

BASE_DIR = Path(__file__).resolve().parent.parent

# ✅ .env 로드
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / ".env")
except Exception:
    pass
# .env 사용 중이면 python-dotenv/django-environ으로 로드해도 OK
GNEWS_KEY = os.getenv("GNEWS_KEY", "")
GUARDIAN_KEY = os.getenv("GUARDIAN_KEY", "")
NAVER_CLIENT_ID = os.getenv("NAVER_CLIENT_ID", "")
NAVER_CLIENT_SECRET = os.getenv("NAVER_CLIENT_SECRET", "")
#==========================================================#

DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "paper",#논문 상세,
    "author",#저자 상세
    'affiliation',#기관 상세
    "country",#국가 상세
    "keywords",#키워드 상세
    "search", # 검색
    # ✅ main은 Config 버전으로만 등록
    "main.apps.MainConfig",  # 임베딩 모델 + 인기자료 뉴스 초기화
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "capstone.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'main.context_processors.part_context',
            ],
        },
    },
]

WSGI_APPLICATION = "capstone.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': '',  # MariaDB에 생성한 데이터베이스 이름
        'USER': '',  # MariaDB에서 생성한 사용자 이름
        'PASSWORD': '',  # MariaDB에서 설정한 비밀번호
        'HOST': '',  # MariaDB 호스트 (기본값 'localhost' 또는 '
        'PORT': '',  # MariaDB 포트 (기본값 3306)
        'OPTIONS': {'charset': 'utf8mb4'},
        'TEST': {
            'CHARSET': 'utf8mb4',
            'COLLATION': 'utf8_general_ci',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "main/static",  # main 앱의 static 폴더 경로\
    BASE_DIR / "search" / "static",
    BASE_DIR / "paper" / "static",
    BASE_DIR / "author" / "static",
    BASE_DIR / "affiliation" / "static",
    BASE_DIR / "country" / "static",
    BASE_DIR / "keyword" / "static",
]


# ✅ Static 파일을 모을 경로 추가
STATIC_ROOT = BASE_DIR / "staticfiles"

WKHTMLTOPDF_PATH = "/usr/bin/wkhtmltopdf"



# ✅ 기존 PDF 저장 경로 유지
MEDIA_URL = '/media/'  # 미디어 파일 URL 경로
MEDIA_ROOT = os.path.join(BASE_DIR, "main", "pdfs")  # ✅ 프로젝트 루트 기준 절대경로 설정


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'djaxodbs010@gmail.com'  # 실제 Gmail 계정
EMAIL_HOST_PASSWORD = 'gdajoryvcdgnfgha'  # 구글 앱 비밀번호(비밀번호 찾기에서 사용)

# ✅ HTTPS 설정 해제 (로컬 개발 환경에서만)
SESSION_COOKIE_SECURE = False  # 🔥 HTTPS에서만 동작하는 쿠키 설정 해제
CSRF_COOKIE_SECURE = False  # 🔥 CSRF 쿠키도 HTTPS에서만 동작하는 문제 방지
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 🔥 브라우저를 닫아도 세션 유지
SESSION_COOKIE_AGE = 86400  # 🔥 1일 동안 로그인 유지 (기본값)
SESSION_COOKIE_SAMESITE = 'Lax'


# import os
# from dotenv import load_dotenv

# # .env 파일 로드
# dotenv_path = os.path.join(os.path.dirname(__file__), '..', '.env')  # ✅ `.env` 파일 경로 지정
# load_dotenv(dotenv_path)

# # 환경 변수에서 API 키 가져오기
# OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")


