# Generated by Django 4.2.17 on 2025-01-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="affiliation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "affiliation",
            },
        ),
        migrations.CreateModel(
            name="author",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("affiliation", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "author",
            },
        ),
        migrations.CreateModel(
            name="country",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("alpha_2", models.CharField(max_length=2)),
                ("alpha_3", models.CharField(max_length=3)),
            ],
            options={
                "db_table": "country",
            },
        ),
        migrations.CreateModel(
            name="keyword",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("keyword_name", models.TextField()),
            ],
            options={
                "db_table": "keyword",
            },
        ),
        migrations.CreateModel(
            name="paper",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("search_keyword", models.TextField()),
                ("title", models.TextField()),
                ("year", models.IntegerField()),
                ("citation", models.IntegerField()),
                ("site", models.TextField()),
                ("paper_url", models.TextField(unique=True)),
                ("published_in", models.CharField(max_length=255)),
                ("abstract", models.TextField()),
                ("saved_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "paper",
            },
        ),
        migrations.CreateModel(
            name="part",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("part_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "part",
            },
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("user_name", models.CharField(max_length=150, unique=True)),
                ("email", models.CharField(max_length=254)),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
