# Generated by Django 4.2.17 on 2025-01-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="searchkeyword",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("keyword", models.TextField()),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "searchkeyword",
            },
        ),
    ]
