# Generated by Django 4.2.17 on 2025-01-11 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_searchkeyword"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paper_part",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "paper_id",
                    models.ForeignKey(
                        db_column="paper_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_papers",
                        to="main.paper",
                    ),
                ),
                (
                    "part_id",
                    models.ForeignKey(
                        db_column="part_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_parts",
                        to="main.part",
                    ),
                ),
            ],
            options={
                "db_table": "paper_part",
            },
        ),
        migrations.CreateModel(
            name="Paper_keyword",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "keyword_id",
                    models.ForeignKey(
                        db_column="keyword_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyword_keywords",
                        to="main.keyword",
                    ),
                ),
                (
                    "paper_id",
                    models.ForeignKey(
                        db_column="paper_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyword_papers",
                        to="main.paper",
                    ),
                ),
            ],
            options={
                "db_table": "paper_keyword",
            },
        ),
        migrations.CreateModel(
            name="Paper_affiliation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "affiliation_id",
                    models.ForeignKey(
                        db_column="affiliation_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliation_keywords",
                        to="main.affiliation",
                    ),
                ),
                (
                    "paper_id",
                    models.ForeignKey(
                        db_column="paper_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliation_papers",
                        to="main.paper",
                    ),
                ),
            ],
            options={
                "db_table": "paper_affiliation",
            },
        ),
    ]
