# Generated by Django 4.2.17 on 2025-01-11 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_paper_part_paper_keyword_paper_affiliation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paper_country",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "author_id",
                    models.ForeignKey(
                        db_column="country_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country_countrys",
                        to="main.country",
                    ),
                ),
                (
                    "paper_id",
                    models.ForeignKey(
                        db_column="paper_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country_papers",
                        to="main.paper",
                    ),
                ),
            ],
            options={
                "db_table": "paper_country",
            },
        ),
        migrations.CreateModel(
            name="Paper_author",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "author_id",
                    models.ForeignKey(
                        db_column="author_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_authors",
                        to="main.author",
                    ),
                ),
                (
                    "paper_id",
                    models.ForeignKey(
                        db_column="paper_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_papers",
                        to="main.paper",
                    ),
                ),
            ],
            options={
                "db_table": "paper_author",
            },
        ),
    ]
