# Generated by Django 4.2.17 on 2025-01-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_paper_country_paper_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paper_country",
            old_name="author_id",
            new_name="country_id",
        ),
    ]
