# Generated by Django 4.2.17 on 2025-01-11 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0005_rename_author_id_paper_country_country_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedPart",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "part_id",
                    models.ForeignKey(
                        db_column="part_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.part",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "savedpart",
            },
        ),
        migrations.CreateModel(
            name="SavedPaper",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper_id",
                    models.ForeignKey(
                        db_column="paper_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.paper",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "savedpaper",
            },
        ),
        migrations.CreateModel(
            name="RecentPaper",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("viewed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "paper_id",
                    models.ForeignKey(
                        db_column="paper_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.paper",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recentpaper",
                "ordering": ["-viewed_at"],
            },
        ),
    ]
