# Generated by Django 4.2.17 on 2025-01-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_savedpart_savedpaper_recentpaper"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="affiliation",
            field=models.TextField(),
        ),
    ]
