# Generated by Django 4.2.17 on 2025-01-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_author_affiliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="affiliation",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
