# Generated by Django 4.2.17 on 2025-01-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_paper_affiliation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="affiliation",
        ),
    ]
