# Generated by Django 5.1.5 on 2025-02-20 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_recentpaper_user_id_alter_savedpaper_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpaper',
            name='part_id',
            field=models.ForeignKey(db_column='part_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='main.part'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SavedPart',
        ),
    ]
