# Generated by Django 5.1.5 on 2025-02-22 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_savedpaper_part_id_delete_savedpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='country_id',
            field=models.ForeignKey(db_column='country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.country'),
        ),
    ]
