# Generated by Django 5.1.5 on 2025-02-25 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_affiliation_country_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_Affiliation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('affiliation_id', models.ForeignKey(db_column='affiliation_id', on_delete=django.db.models.deletion.CASCADE, to='main.affiliation')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'db_table': 'like_affiliation',
                'unique_together': {('affiliation_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='Like_Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('author_id', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, to='main.author')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'db_table': 'like_author',
                'unique_together': {('author_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='Like_Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('country_id', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, to='main.country')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'db_table': 'like_country',
                'unique_together': {('country_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='Like_Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('keyword_id', models.ForeignKey(db_column='keyword_id', on_delete=django.db.models.deletion.CASCADE, to='main.keyword')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'db_table': 'like_keyword',
                'unique_together': {('keyword_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='Like_Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('paper_id', models.ForeignKey(db_column='paper_id', on_delete=django.db.models.deletion.CASCADE, to='main.paper')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'db_table': 'like_paper',
                'unique_together': {('paper_id', 'user_id')},
            },
        ),
    ]
