# Generated by Django 5.1.5 on 2025-03-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_fulltext_index'),
        ('main', '0013_like_affiliation_like_author_like_country_and_more'),
    ]

    operations = [
    ]
