# Generated by Django 5.1.5 on 2025-03-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_merge_20250303_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword_name',
            field=models.TextField(unique=True),
        ),
    ]
