# Generated by Django 5.1.5 on 2025-03-18 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_keyword_keyword_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(blank=True, null=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='main.paper')),
            ],
            options={
                'db_table': 'paper_embedding',
            },
        ),
    ]
