# Generated by Django 5.1.5 on 2025-09-10 00:47

import django.utils.timezone
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_paperembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.BigIntegerField()),
                ('query', models.CharField(max_length=500)),
                ('provider', models.CharField(choices=[('gnews', 'GNews'), ('guardian', 'Guardian'), ('gdelt', 'GDELT'), ('newsapi', 'NewsAPI')], max_length=20)),
                ('results_json', models.JSONField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=main.models.default_expires_at)),
            ],
            options={
                'db_table': 'news_cache',
                'indexes': [models.Index(fields=['paper_id', 'query', 'provider'], name='news_cache_paper_i_aa30e7_idx'), models.Index(fields=['expires_at'], name='news_cache_expires_cd5c40_idx')],
            },
        ),
    ]
