# Generated by Django 5.1.5 on 2025-10-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_newscache'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperembedding',
            name='norm_vector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paperembedding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
