# Generated by Django 5.1.5 on 2025-09-10 00:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like_Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'like_paper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('search_keyword', models.TextField()),
                ('title', models.TextField()),
                ('year', models.IntegerField()),
                ('citation', models.IntegerField()),
                ('site', models.TextField()),
                ('paper_url', models.TextField(unique=True)),
                ('published_in', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('saved_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'paper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paper_author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'paper_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paper_keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'paper_keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paper_part',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'paper_part',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecentPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'recentpaper',
                'ordering': ['-viewed_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SavedPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'savedpaper',
                'managed': False,
            },
        ),
    ]
